Sprint6
ClevertecFrontendLab/DmitriyVoronovich pull request #7
Opened 2024-04-10 09:49 UTC by DmitriyVoronovich

2024-04-10 09:52 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712742766/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712742766/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712742766/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712742766/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712742766/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712742766/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712742766/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712742766/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712742766/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712742766/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712742766/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712742766/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712742766/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712742766/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712742766/update-trainings-3_360x740.png)

2024-04-10 11:54 UTC, SergeyGlazun requested changes
![image](https://github.com/ClevertecFrontendLab/DmitriyVoronovich/assets/70904466/52b37274-8be7-4eaa-9234-1da86845e638)
не работает возрат по хлебным крошка и хороше бы оцентровать приложение для широкоформатных мониторов

2024-04-10 11:54 UTC, SergeyGlazun commented
![image](https://github.com/ClevertecFrontendLab/DmitriyVoronovich/assets/70904466/6fc73aa2-475e-4d00-856e-c3f1c03c4ef3)
также не работают боковые вкладки

2024-04-10 12:00 UTC, SergeyGlazun commented
![image](https://github.com/ClevertecFrontendLab/DmitriyVoronovich/assets/70904466/d6ead70e-b593-4821-84b9-fdade4b4f5e4)
моступна кнопка без названия упражнения

2024-04-10 13:45 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712756720/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712756720/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712756720/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712756720/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712756720/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712756720/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712756720/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712756720/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712756720/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712756720/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712756720/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712756720/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712756720/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712756720/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712756720/update-trainings-3_360x740.png)

2024-04-10 17:03 UTC, SergeyGlazun requested changes
![image](https://github.com/ClevertecFrontendLab/DmitriyVoronovich/assets/70904466/a22bbbaf-dfde-4433-8423-738d2b386404)
если ввести, а потом удалить значение кнопка доступна

2024-04-10 19:50 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712778601/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712778601/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712778601/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712778601/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712778601/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712778601/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712778601/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712778601/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712778601/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712778601/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712778601/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712778601/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712778601/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712778601/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712778601/update-trainings-3_360x740.png)

2024-04-10 19:56 UTC, ValadzkoAliaksei requested changes

2024-04-10 19:56 UTC, ValadzkoAliaksei commented on src/common/components/sidebar/index.tsx
> +                <div className={`${
попробуй библиотечку https://www.npmjs.com/package/classnames

2024-04-10 19:56 UTC, ValadzkoAliaksei commented on src/features/training/ui/joint-training-block/user-joint-training-list/index.tsx
> +
я так понимаю линтеры не настроены?)

2024-04-10 20:00 UTC, ValadzkoAliaksei requested changes

2024-04-10 20:00 UTC, ValadzkoAliaksei commented on src/app/ui/App.tsx
> +import { getToken } from '@utils/getToken.ts';
https://github.com/ClevertecFrontendLab/DmitriyVoronovich/assets/61273546/d5f11c88-88c2-4163-9663-253cc7be823a

github-pages не работает(

2024-04-10 20:34 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781273/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781273/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781273/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781273/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781273/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781273/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781273/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781273/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781273/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781273/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781273/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781273/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781273/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781273/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781273/update-trainings-3_360x740.png)

2024-04-10 20:42 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781729/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781729/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781729/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781729/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781729/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781729/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781729/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781729/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781729/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781729/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781729/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781729/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781729/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781729/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712781729/update-trainings-3_360x740.png)

2024-04-10 20:47 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712782032/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712782032/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712782032/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712782032/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712782032/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712782032/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712782032/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712782032/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712782032/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712782032/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712782032/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712782032/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712782032/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712782032/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712782032/update-trainings-3_360x740.png)

2024-04-10 20:55 UTC, SergeyGlazun requested changes
![image](https://github.com/ClevertecFrontendLab/DmitriyVoronovich/assets/70904466/a9369c94-40aa-4f9a-919c-5576e9abff09)
не могу редактировать из календаря

2024-04-10 20:56 UTC, SergeyGlazun commented
![image](https://github.com/ClevertecFrontendLab/DmitriyVoronovich/assets/70904466/195f84d8-4e77-483f-9bfa-2a1048f0db7e)
тут бы хотелось видеть курсор поинтер когда наводишь

2024-04-11 04:41 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712810513/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712810513/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712810513/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712810513/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712810513/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712810513/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712810513/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712810513/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712810513/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712810513/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712810513/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712810513/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712810513/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712810513/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/DmitriyVoronovich/1712810513/update-trainings-3_360x740.png)

2024-04-11 04:43 UTC, DmitriyVoronovich commented
Что касается редактирования тренировок в календаре, локально у меня все работает, все кликается. В консоли не падает ошибок связанных с этим действием и при редактировании всё отрабатывает как нужно. К сожалению я не могу воспроизвести ошибку локально.
![Screenshot_1](https://github.com/ClevertecFrontendLab/DmitriyVoronovich/assets/106402177/2cae9947-6d58-4662-ac58-3400599cee9c)

2024-04-11 07:03 UTC, SergeyGlazun approved these changes

2024-04-11 09:35 UTC, ValadzkoAliaksei approved these changes

2024-04-11 09:49 UTC, merged